"""" List of prioritized fields in output CSV """

fieldnames = [
    "id",
    "field_type_of_resource",
    "field_resource_type",
    "field_genre",
    "field_related_title",
    "field_related_title_part_of",
    "field_related_title_preceding",
    "field_related_title_succeeding",
    "field_related_title_constituent",
    "field_related_title_original",
    "field_related_title_other_format",
    "field_related_title_other_versio",
    "field_related_title_referenced",
    "field_full_title",
    "title",
    "field_linked_agent",
    "field_publisher_pitt",
    "field_place_publication",
    "field_place_production",
    "field_note",
    "field_music_publisher_number",
    "field_distributor",
    "field_local_identifier",
    "field_place_manufacture",
    "field_manufacturer",
    "field_table_of_contents",
    "field_producer",
    "field_source_collection",
    "field_physical_form",
    "field_uniform_title",
    "field_edtf_date",
    "field_extent",
    "field_statement_of_resp",
    "field_subject_genre",
    "field_subject",
    "field_language",
    "field_temporal_subject",
    "field_muscomp_genre",
    "field_alternative_title_pitt",
    "field_edition",
    "field_description_long",
    "field_depositor",
    "field_mode_of_issuance",
    "field_geographic_subject",
    "field_copyright_date",
    "field_rights_statement",
    "field_oclc_number",
    "field_subjects_name",
    "field_place_distribution",
    "field_record_source_id",
    "field_place_published_pitt",
]


""" Dictionary used to rename target  columns in output CSV """

columns = {
    'identifier@pitt': 'identifier',
    'titleInfo/title': 'title', 
    'typeOfResource': 'type_of_resource',
    'originInfo/publisher': 'publisher',
    'originInfo/placeTerm@text': 'pub_place',
    'originInfo/dateOther@display': 'DELETE_display_date', 
    'originInfo/dateOther@sort': 'DELETE_sort_date',
    'language/languageTerm@code': 'language', 
    'originInfo/dateCreated': 'normalized_date', 
    'originInfo/dateCaptured': 'date_digitized',
    'abstract': 'description', 
    'physicalDescription/form': 'format', 
    'physicalDescription/extent': 'extent',
    'genre@aat': 'genre_aat', 
    'relatedItem@host/titleInfo/title': 'CHECK_source_collection',
    #'relatedItem/titleInfo/title': 'source_collection', # Remove once CSV-to-MODS utility updated
    'relatedItem@host/dateCreated': 'source_collection_date', 
    'relatedItem@host/identifier': 'source_collection_id', 
    'relatedItem@host/identifier@local-asc': 'source_collection_id', 
    'relatedItem@host/note@ownership': 'source_ownership',
    'relatedItem@host/note@prefercite': 'source_citation', 
    'relatedItem/note@prefercite': 'source_citation', 
    'relatedItem@host/note@container': 'source_container',
    'relatedItem@host/note@series': 'source_series', 
    'relatedItem@host/note@subseries': 'source_subseries', 
    'relatedItem@host/note@otherlevel': 'source_other_level',
    'identifier@source': 'source_id', 
    'name/rights.holder/copyright/accessCondition': 'rights_holder', 
    'note@address': 'address', 
    'note@donor': 'gift_of',
    }


""" Namespaces Info """

namespaces = {
    'mods_ns': {
        'mods': 'http://www.loc.gov/mods/v3'
        },
    'copyright_ns': {
        'copyrightMD': 'http://www.cdlib.org/inside/diglib/copyrightMD'
        }
    }


mods_ns = '{http://www.loc.gov/mods/v3}'
copyrightMD_ns = '{http://www.cdlib.org/inside/diglib/copyrightMD}'


RELATORS = {
    "abridger": "abr",
    "actor": "act",
    "adapter": "adp",
    "addressee": "rcp",
    "analyst": "anl",
    "animator": "anm",
    "annotator": "ann",
    "announcer": "anc",
    "appellant": "apl",
    "appellee": "ape",
    "applicant": "app",
    "appraiser": "exp",
    "architect": "arc",
    "arranger": "arr",
    "arranger of music": "arr",
    "art copyist": "acp",
    "art director": "adi",
    "artist": "art",
    "artistic director": "ard",
    "assignee": "asg",
    "associated name": "asn",
    "attributed name": "att",
    "auctioneer": "auc",
    "audio engineer": "aue",
    "audio producer": "aup",
    "author": "aut",
    "author in quotations or text abstracts": "aqt",
    "author of afterword, colophon, etc.": "waw",
    "author of dialog": "aud",
    "author of introduction, etc.": "waw|win|wpr",
    "author of screenplay, etc.": "aus",
    "autographer": "ato",
    "bibliographic antecedent": "ant",
    "binder": "bnd",
    "binding designer": "bdd",
    "blurb writer": "blw",
    "book artist": "bka",
    "book designer": "bkd",
    "book producer": "bkp",
    "bookjacket designer": "bjd",
    "bookplate designer": "bpd",
    "bookseller": "bsl",
    "bowdlerizer": "cns",
    "braille embosser": "brl",
    "broadcaster": "brd",
    "calligrapher": "cll",
    "camera operator": "cop",
    "cartographer": "ctg",
    "caster": "cas",
    "casting director": "cad",
    "censor": "cns",
    "chief electrician": "elg",
    "choral conductor": "cnd",
    "choreographer": "chr",
    "cinematographer": "cng",
    "civil defendant": "dfd",
    "client": "cli",
    "collaborator": "ctb",
    "collection registrar": "cor",
    "collector": "col",
    "collotyper": "clt",
    "colorist": "clr",
    "colourist": "clr",
    "commentator": "cmm",
    "commentator for written text": "cwt",
    "commissioning body": "pat",
    "compiler": "com",
    "complainant": "cpl",
    "complainant-appellant": "cpt",
    "complainant-appellee": "cpe",
    "composer": "cmp",
    "compositor": "cmt",
    "conceptor": "ccp",
    "conductor": "cnd",
    "conservator": "con",
    "consultant": "csl",
    "consultant to a project": "csp",
    "contestant": "cos",
    "contestant-appellant": "cot",
    "contestant-appellee": "coe",
    "contestee": "cts",
    "contestee-appellant": "ctt",
    "contestee-appellee": "cte",
    "contractor": "ctr",
    "contributor": "ctb",
    "copier": "fac|frg",
    "copyright claimant": "cpc",
    "copyright holder": "cph",
    "corrector": "crr",
    "correspondent": "crp",
    "costume designer": "cst",
    "counterfeiter": "frg",
    "court governed": "cou",
    "court reporter": "crt",
    "cover designer": "cov",
    "creator": "cre",
    "criminal defendant": "dfd",
    "curator": "cur",
    "curator of an exhibition": "cur",
    "current owner": "own",
    "dancer": "dnc",
    "data contributor": "dtc",
    "data manager": "dtm",
    "dedicatee": "dte",
    "dedicatee of item": "dte",
    "dedicator": "dto",
    "defendant": "dfd",
    "defendant-appellant": "dft",
    "defendant-appellee": "dfe",
    "degree committee member": "dgc",
    "degree granting institution": "dgg",
    "degree grantor": "dgg",
    "degree supervisor": "dgs",
    "delineator": "dln",
    "depicted": "dpc",
    "deponent": "wit",
    "depositor": "dpt",
    "designer": "dsr",
    "designer of binding": "bdd",
    "designer of book": "bkd",
    "designer of bookjacket": "bjd",
    "designer of cover": "cov",
    "designer of e-book": "bkd",
    "designer of type": "tyd",
    "director": "drt",
    "director of photography": "cng",
    "dissertant": "dis",
    "distribution place": "dbp",
    "distributor": "dst",
    "dj": "djo",
    "donor": "dnr",
    "draftsman": "drm",
    "dubbing director": "dbd",
    "dubious author": "dub",
    "editor": "edt",
    "editor of compilation": "edc",
    "editor of moving image work": "edm",
    "editorial director": "edd",
    "electrician": "elg",
    "electrotyper": "elt",
    "enacting jurisdiction": "enj",
    "encoder": "mrk",
    "engineer": "eng",
    "engraver": "egr",
    "etcher": "etr",
    "event place": "evp",
    "expert": "exp",
    "expurgator": "cns",
    "eyewitness": "wit",
    "facsimilist": "fac",
    "field director": "fld",
    "film director": "fmd",
    "film distributor": "fds",
    "film editor": "flm",
    "film producer": "fmp",
    "filmmaker": "fmk",
    "first party": "fpy",
    "forger": "frg",
    "former owner": "fmo",
    "founder": "fon",
    "funder": "fnd",
    "game developer": "gdv",
    "geographic information specialist": "gis",
    "geospatial information specialist": "gis",
    "graphic technician": "art",
    "honoree": "hnr",
    "honouree": "hnr",
    "honouree of item": "hnr",
    "host": "hst",
    "host institution": "his",
    "host, supporting": "sht",
    "house electrician": "elg",
    "illuminator": "ilu",
    "illustrator": "ill",
    "imprimatur": "lso",
    "inker": "ink",
    "inscriber": "ins",
    "instructor": "tch",
    "instrumental conductor": "cnd",
    "instrumentalist": "itr",
    "interviewee": "ive",
    "interviewer": "ivr",
    "inventor": "inv",
    "issuing body": "isb",
    "joint author": "aut",
    "judge": "jud",
    "jurisdiction governed": "jug",
    "lab director": "ldr",
    "laboratory": "lbr",
    "laboratory director": "ldr",
    "landscape architect": "lsa",
    "lead": "led",
    "lender": "len",
    "letterer": "ltr",
    "libelant": "lil",
    "libelant-appellant": "lit",
    "libelant-appellee": "lie",
    "libelee": "lel",
    "libelee-appellant": "let",
    "libelee-appellee": "lee",
    "librettist": "lbt",
    "licensee": "lse",
    "licensor": "lso",
    "lighting designer": "lgd",
    "lithographer": "ltg",
    "lyricist": "lyr",
    "makeup artist": "mka",
    "manufacture place": "mfp",
    "manufacturer": "mfr",
    "marbler": "mrb",
    "markup editor": "mrk",
    "master electrician": "elg",
    "medium": "med",
    "metadata contact": "mdc",
    "metal-engraver": "mte",
    "minute taker": "mtk",
    "mixing engineer": "mxe",
    "moderator": "mod",
    "monitor": "mon",
    "motion picture editor": "flm",
    "moving image work editor": "edm",
    "music copyist": "mcp",
    "music programmer": "mup",
    "musical director": "msd",
    "musician": "mus",
    "narrator": "nrt",
    "news anchor": "nan",
    "observer": "wit",
    "onlooker": "wit",
    "onscreen participant": "onp",
    "onscreen presenter": "osp",
    "opponent": "opn",
    "organizer": "orm",
    "organizer of meeting": "orm",
    "originator": "org",
    "other": "oth",
    "owner": "own",
    "panelist": "pan",
    "papermaker": "ppm",
    "patent applicant": "pta",
    "patent holder": "pth",
    "patent inventor": "inv",
    "patentee": "pth",
    "patron": "pat",
    "penciller": "pnc",
    "performer": "prf",
    "performer of research": "res",
    "permitting agency": "pma",
    "photographer": "pht",
    "place of address": "pad",
    "plaintiff": "ptf",
    "plaintiff corporate body": "ptf",
    "plaintiff person": "ptf",
    "plaintiff-appellant": "ptt",
    "plaintiff-appellee": "pte",
    "platemaker": "plt",
    "plates, printer of": "pop",
    "praeses": "pra",
    "presenter": "pre",
    "preservationist": "con",
    "printer": "prt",
    "printer of plates": "pop",
    "printmaker": "prm",
    "process contact": "prc",
    "producer": "pro",
    "producer of book": "bkp",
    "production company": "prn",
    "production designer": "prs",
    "production manager": "pmn",
    "production place": "prp",
    "programmer": "prg",
    "project director": "pdr",
    "project supervisor": "pdr",
    "promoter": "ths",
    "proofreader": "pfr",
    "provider": "prv",
    "publication place": "pup",
    "publisher": "pbl",
    "publishing director": "pbd",
    "puppeteer": "ppt",
    "radio director": "rdd",
    "radio producer": "rpc",
    "rapporteur": "rap",
    "recipient": "rcp",
    "recording engineer": "rce",
    "recordist": "rcd",
    "redaktor": "red",
    "remix artist": "rxa",
    "renderer": "ren",
    "reporter": "rpt",
    "repository": "rps",
    "research supervisor": "rth",
    "research team head": "rth",
    "research team member": "rtm",
    "researcher": "res",
    "respondent": "rsp",
    "respondent-appellant": "rst",
    "respondent-appellee": "rse",
    "responsible party": "rpy",
    "restager": "rsg",
    "restorationist": "rsr",
    "reviewer": "rev",
    "rubricator": "rbr",
    "scenarist": "sce",
    "scientific advisor": "sad",
    "screenwriter": "aus",
    "scribe": "scr",
    "sculptor": "scl",
    "second party": "spy",
    "secretary": "sec",
    "seller": "sll",
    "set designer": "std",
    "setting": "stg",
    "signer": "sgn",
    "singer": "sng",
    "software developer": "swd",
    "sound designer": "sds",
    "sound engineer": "sde",
    "speaker": "spk",
    "special effects provider": "sfx",
    "sponsor": "spn",
    "sponsored work": "spn",
    "sponsoring body": "spn",
    "stage director": "sgd",
    "stage manager": "stm",
    "standards body": "stn",
    "stereotyper": "str",
    "storyteller": "stl",
    "supporting host": "sht",
    "supposed name": "att",
    "surveyor": "srv",
    "teacher": "tch",
    "technical advisor": "tad",
    "technical director": "tcd",
    "technical draftsman": "drm",
    "television director": "tld",
    "television guest": "tlg",
    "television host": "tlh",
    "television producer": "tlp",
    "television writer": "tau",
    "testifier": "wit",
    "thesis advisor": "ths",
    "transcriber": "trc",
    "translator": "trl",
    "type designer": "tyd",
    "typesetter": "cmt",
    "typographer": "tyg",
    "university place": "uvp",
    "videographer": "vdg",
    "visual effects provider": "vfx",
    "vocalist": "sng",
    "voice actor": "vac",
    "witness": "wit",
    "wood engraver": "wde",
    "woodcutter": "wdc",
    "writer of accompanying material": "wam",
    "writer of added commentary": "wac",
    "writer of added lyrics": "wal",
    "writer of added text": "wat",
    "writer of afterword": "waw",
    "writer of film story": "wfs",
    "writer of foreword": "wfw",
    "writer of intertitles": "wft",
    "writer of introduction": "win",
    "writer of postface": "waw",
    "writer of preface": "wpr",
    "writer of supplementary textual content": "wst",
    "writer of television story": "wts",
}
